apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo-simple.fullname" . }}
  labels:
    {{- include "odoo-simple.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "odoo-simple.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "odoo-simple.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.odoo.addonsImage }}
      initContainers:
        - name: init
          image: "{{ .Values.odoo.addonsImage }}"
          command:
            - sh
            - "-c"
            - "cp -R /mnt/extra-addons/* /mnt/extra-addons/.??* /mnt/dest-addons/"
          volumeMounts:
            - mountPath: /mnt/dest-addons
              name: addons
      {{- end }}
      containers:
        - name: {{ template "odoo-simple.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
    {{- if .Values.odoo.command }}
    {{- with .Values.odoo.command }}
          command:
            {{- toYaml . | nindent 12 }}
    {{- end }}
    {{- end }}
          volumeMounts:
            {{- if .Values.odoo.addonsImage }}
            - name: addons
              mountPath: /mnt/extra-addons
            {{- end }}
            - name: data
              mountPath: /var/lib/odoo
    {{- if .Values.odoo.config }}
            - name: config
              mountPath: /etc/odoo/odoo.conf
              subPath: odoo.conf
    {{- end }}
          env:
            - name: HOST
              value: {{ required "database.host is a required value." .Values.database.host }}
            - name: USER
              value: {{ required "database.user is a required value." .Values.database.user }}
            - name: PORT
              value: "{{ .Values.database.port | default 5432 }}"

          envFrom:
            - secretRef:
                name: {{ include "odoo-simple.fullname" . }}
            - configMapRef:
                name: {{ include "odoo-simple.fullname" . }}
          ports:
            - name: http
              containerPort: 8069
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /web/database/manager
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /web/database/manager
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: addons
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "odoo-simple.fullname" .) }}
    {{- if .Values.odoo.config }}
        - name: config
          configMap:
            name: {{ .Values.odoo.config }}
    {{- end }}
