apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo-simple.fullname" . }}
  labels:
    {{- include "odoo-simple.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "odoo-simple.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "odoo-simple.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /entrypoint.sh
            - "--"
            - "-d"
            - {{ .Values.database.name }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/odoo
    {{- if .Values.odooConfig }}
            - name: config
              mountPath: /etc/odoo.conf
              subPath: odoo.conf
    {{- end }}
          env:
            - name: HOST
              value: "{{ required "database.host is a required value." .Values.database.host }}"
            - name: USER
              value: "{{ required "database.user is a required value." .Values.database.user }}"
            - name: PORT
              value: {{ .Values.database.port | default "5432" }}

          envFrom:
            - secretRef:
                name: {{ include "odoo-simple.fullname" . }}
            - configMapRef:
                name: {{ include "odoo-simple.fullname" . }}
          ports:
            - name: http
              containerPort: 8069
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "odoo-simple.fullname" .) }}
    {{- if .Values.odooConfig }}
        - name: config
          configMap:
            name: {{ if .Values.odooConfig }}
    {{- end }}
