apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo-simple.fullname" . }}
  labels:
    {{- include "odoo-simple.labels" . | nindent 4 }}
type: Opaque
data:
  PASSWORD: {{ required "databasePassword is a required value." .Values.database.password | b64enc | quote }}
