apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo-simple.fullname" . }}-longpolling
  labels:
    {{- include "odoo-simple.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8072
      protocol: TCP
      name: http
  selector:
    {{- include "odoo-simple.selectorLabels" . | nindent 4 }}
